name: Latest blog post workflow
on:
  schedule:
    - cron: '30 5,17 * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shingo-kumada/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https://qiita.com/shingo-kumada"
