name: GitHub Skyline
uses: shingo-kumada/metrics@master
with:
  filename: metrics.plugin.skyline.svg
  token: NOT_NEEDED
  base: ""
  plugin_skyline: yes
  plugin_skyline_year: 2023
  plugin_skyline_frames: 6
  plugin_skyline_quality: 1
